### ISSUE TITLE
Issues with the Serbian language

### ISSUE THREAD

**Issue by insxa** [FOSSBilling/locale#212]
### Describe the bug

I have put request here https://forum.fossbilling.org/d/112-fossbilling-translation

### How to reproduce

Language Serbian should use latin letter instead cyrilic

### Expected behavior

Name in locale/locales.php should be instead 'sr_RS' => 'Српски', -> 'sr_RS' => 'Srpski',
Folder name froom srp to sr_RS

### FOSSBilling version

0.5.6

**Comment by BelleNottelling** [comment]
I believe this is now fixed, but we will have to wait a bit for the next Crowdin sync to see if what I setup works as intended

**Comment by BelleNottelling** [comment]
Should be fixed for all future releases
